#!/bin/sh

. /lib/functions/system.sh
. /lib/functions/uci-defaults.sh

ipq40xx_setup_interfaces()
{
	local board="$1"

	case "$board" in
	davolink,dv01-901h)
		ucidef_set_interfaces_lan_wan "eth0" "eth1"
		ucidef_add_switch "switch0" 			"0u@eth0" "1:lan:4" "2:lan:3" "3:lan:2" "4:lan:1"
		;;
	*)
		ucidef_set_interfaces_lan_wan "eth0" "eth1"
		;;
	esac
}

ipq40xx_setup_macs()
{
	local board="$1"
	local lan_mac=""
	local wan_mac=""
	local label_mac=""

	case "$board" in
	davolink,dv01-901h)
		lan_mac=$(mtd_get_mac_binary "vmacs" 0x10)
		wan_mac=$(mtd_get_mac_binary "vmacs" 0x0)
		label_mac=$wan_mac
		;;
	esac

	[ -n "$lan_mac" ] && ucidef_set_interface_macaddr "lan" "$lan_mac"
	[ -n "$wan_mac" ] && ucidef_set_interface_macaddr "wan" "$wan_mac"
	[ -n "$label_mac" ] && ucidef_set_label_macaddr "$label_mac"
}

board_config_update
board=$(board_name)
ipq40xx_setup_interfaces $board
ipq40xx_setup_macs $board
board_config_flush
